# Commands to start on workspace startup
tasks:
  - name: Setup
    init: >
      yarn;
      docker-compose up -d;
      cp .env.example .env.local;
      cp nodemon.json.example nodemon.json;
      yarn build;
      gp sync-done setup;
    command: echo "Setup done"
  - name: Dev Server
    init: gp sync-await setup
    command: yarn dev

# Ports to expose on workspace startup
ports:
  # Nextjs
  - port: 3000
    onOpen: ignore
    visibility: public

  # IPFS
  - port: 80
    onOpen: ignore
    visibility: public
  - port: 4001
    onOpen: ignore
    visibility: public
  - port: 5001
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - bradlc.vscode-tailwindcss
    - bierner.markdown-preview-github-styles
    - pkief.material-icon-theme
