# Commands to start on workspace startup
tasks:
  - name: Setup
    init: >
      yarn;
      docker-compose up -d;
      cp .env.local.example .env.local;
      cp nodemon.json.example nodemon.json;
      yarn build;
      gp sync-done setup;
    command: echo "Setup done"
  - name: Dev Server
    init: gp sync-await setup
    command: yarn dev
  - name: Storybook dev
    init: gp sync-await setup
    command: yarn sb

# Ports to expose on workspace startup
ports:
  # Nextjs
  - port: 3000
    onOpen: ignore
    visibility: public

  # Storybook
  - port: 6006
    onOpen: ignore
    visibility: public

  # IPFS
  - port: 80
    onOpen: ignore
    visibility: public
  - port: 4001
    onOpen: ignore
    visibility: public
  - port: 5001
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - 'pkief.material-icon-theme'
    - 'bradlc.vscode-tailwindcss'
    - 'esbenp.prettier-vscode'
