# Commands to start on workspace startup
tasks:
  - init: >
      yarn install
      docker-compose up -d;
      cp .env.local.example .env.local;
      cp nodemon.json.example nodemon.json;
    command:  yarn dev

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 7687
    onOpen: ignore
    visibility: public
  - port: 7474
    onOpen: notify
    visibility: public
  - port: 27018
    onOpen: ignore
    visibility: public
  - port: 9001
    onOpen: ignore
    visibility: public
  - port: 9002
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - "pkief.material-icon-theme"