tasks:
  - name: Setup
    before: redis-server &
    init: |
      yarn install --frozen-lockfile --silent --network-timeout 100000;
      cp .env.example .env.local;
      yarn build;
    command: yarn dev
  - name: Storybook
    command: yarn sb
ports:
  - port: 3000 # Web app
    onOpen: notify
    visibility: public
  - port: 6006 # Storybook
    onOpen: notify
    visibility: public


vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - esbenp.prettier-vscode
    - wix.vscode-import-cost
    - pkief.material-icon-theme

