# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    name: Build (Node ${{ matrix.node-version }})
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn build

  publish:
    needs: build
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/histories
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest, 0.${{ github.run_number }}'
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          comment: |
            Docker image automatically deployed🥳\
            try `docker pull ${{ secrets.DOCKER_USERNAME }}/histories:0.${{ github.run_number }}`
          token: ${{ secrets.GITHUB_TOKEN }}
