name: Storybook build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, production, dependabot]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Build storybook
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn sb-build
